declare let 멍멍: [string, boolean?];
declare function 함수08(...x: [number, string]): void;
declare function 함수08_1(a: number, b: string): void;
declare let arr: number[];
declare let arr2: [number, number, ...number[]];
declare let 녹차: [string, number, boolean];
declare type Arr = [string, number, ...boolean[]];
declare let 녹차arr: Arr;
declare type 함수타입 = [string, boolean, ...(string | number)[]];
declare function 숙제4함수(...rest: (string | number)[]): void;
